---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - name: "3333"
    port: 3333
    protocol: TCP
    targetPort: 3333
  selector:
    app: service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: service
  replicas: 1
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: service:v0
        ports:
        - containerPort: 3333
        imagePullPolicy: Never # we need this on kind
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3333
            httpHeaders:
            - name: Status
              value: "200"
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service
  annotations: 
    kubernetes.io/ingress.class: nginx  
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service
  targetCPUUtilizationPercentage: 60

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service
spec:
  tls:
  - hosts:
      - localhost
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service
            port:
              number: 3333
